version: '3'
services:
  node:
    build: .
    ports:
      - '3001:3001'
      - '3002:3002'
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
